// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Order is an autogenerated mock type for the Order type
type Order struct {
	mock.Mock
}

// Count provides a mock function with given fields: orderId
func (_m *Order) Count(orderId int) int {
	ret := _m.Called(orderId)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(orderId)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewOrder creates a new instance of Order. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrder(t testing.TB) *Order {
	mock := &Order{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
