// Code generated by MockGen. DO NOT EDIT.
// Source: ./user.go

// Package gomocks is a generated GoMock package.
package gomocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// Age mocks base method.
func (m *MockUser) Age(userId int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Age", userId)
	ret0, _ := ret[0].(int)
	return ret0
}

// Age indicates an expected call of Age.
func (mr *MockUserMockRecorder) Age(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Age", reflect.TypeOf((*MockUser)(nil).Age), userId)
}

// Name mocks base method.
func (m *MockUser) Name(userId int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name", userId)
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockUserMockRecorder) Name(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockUser)(nil).Name), userId)
}
